apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  namespace: default
spec:
  replicas: 1
  template:
    spec: # Pod spec
      containers:
      - name: vote-app
        image: kodekloud/examplevotingapp_vote:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "16Mi" 
            cpu: "50m"    # 500milliCPUs (1/2 CPU)
          limits:
            memory: "128Mi"
            cpu: "100m"